version: '3.9'

services:
  report_forge:
    image: htetlinmaung/report_forge
    ports:
      - "8004:8080"
    environment:
      - "DB_CONNECTION=host=150.95.82.125 user=postgres password=P@ssword dbname=report"
    volumes:
      # - ./fonts:/usr/share/fonts/custom-fonts
      - ./templates:/templates