version: '3.9'

services:
  report_forge:
    image: htetlinmaung/report_forge
    ports:
      - "8080:8080"
    environment:
      - DB_CONNECTION="host=localhost user=postgres password=<password> dbname=<dbname>"
    volumes:
      - ./fonts:/usr/share/fonts/custom-fonts
      - ./templates:/templates